# Generated by Django 3.0.4 on 2020-05-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200503_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobtitle',
            field=models.CharField(default='none', max_length=601),
        ),
    ]
