# Generated by Django 3.0.4 on 2020-05-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200503_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pubdate',
            field=models.DateTimeField(),
        ),
    ]
